# Generated by Django 4.2.11 on 2024-06-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_fix_policy_mutation_name'),
        ('insuree', '0021_family_uuid')
    ]

    def update_uuid(app, schema_editor):
        Policy = app.get_model('policy', 'policy')
        Family = app.get_model('insuree', 'family')

        # Update family_uuid in policy
        for policy in Policy.objects.all():
            if policy.family:
                family = Family.objects.filter(id=policy.family.id).first()
                if family:
                    policy.family_uuid = family.uuid
                    policy.save()

    operations = [
        migrations.AddField(
            model_name='policy',
            name='family_uuid',
            field=models.UUIDField(blank=True, db_column='FamilyUUID', null=True),
        ),
        migrations.RunPython(update_uuid)
    ]
