# Generated by Django 4.2.11 on 2024-06-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_policy_family_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='family',
            field=models.IntegerField(db_column='FamilyID'),
        ),
    ]
