# Generated by Django 4.2.16 on 2025-04-21 12:25

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_auto_20240716_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='payment_day',
            field=models.SmallIntegerField(blank=True, choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20')], db_column='PaymentDay', default=5, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semester'), ('Y', 'Yearly')], db_column='Periodicity', default='M', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='signature_date',
            field=core.fields.DateField(blank=True, db_column='SignatureDate', null=True),
        ),
    ]
