# Generated by Django 4.2.11 on 2024-06-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0030_remove_familymutation_family_uuid_and_more'),
        ('policy', '0009_alter_policy_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='family',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='family_uuid',
            new_name='family'
        ),
        migrations.AlterField(
            model_name='policy',
            name='family',
            field=models.ForeignKey(blank=True, db_column='FamilyUUID', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='policies', to='insuree.family'),
        ),
    ]
