# Generated by Django 4.2.30 on 2026-09-02 16:52

import core.fields
import core.models.base_mutation
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_auto_20230510_1347"),
        ("insuree", "0030_family_confirmation_type_family_family_type_and_more"),
        (
            "core",
            "0032_rename_core_userbu_user_id_c9ca53_idx_core_userbu_user_id_57d1ee_idx_and_more",
        ),
        ("policy", "0010_add_field_pregnancy_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyRenewalMutation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "policy_renewal_PolicyMutation",
                "managed": True,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
        migrations.AddField(
            model_name="policy",
            name="family",
            field=models.ForeignKey(
                db_column="FamilyID",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="policies",
                to="insuree.family",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="officer",
            field=models.ForeignKey(
                blank=True,
                db_column="OfficerID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="policies",
                to="core.officer",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="product",
            field=models.ForeignKey(
                db_column="ProdID",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="policies",
                to="product.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="uuid",
            field=models.CharField(
                db_column="PolicyUUID", default=uuid.uuid4, max_length=36, unique=True
            ),
        ),
        migrations.AddField(
            model_name="policyrenewal",
            name="insuree",
            field=models.ForeignKey(
                db_column="InsureeID",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="policy_renewals",
                to="insuree.insuree",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policyrenewal",
            name="new_officer",
            field=models.ForeignKey(
                blank=True,
                db_column="NewOfficerID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="policy_renewals",
                to="core.officer",
            ),
        ),
        migrations.AddField(
            model_name="policyrenewal",
            name="new_product",
            field=models.ForeignKey(
                db_column="NewProdID",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="policy_renewals",
                to="product.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policyrenewal",
            name="policy",
            field=models.ForeignKey(
                db_column="PolicyID",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="policy_renewals",
                to="policy.policy",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="policy",
            name="validity_from",
            field=core.fields.DateTimeField(
                db_column="ValidityFrom", default=datetime.datetime.now
            ),
        ),
        migrations.AddConstraint(
            model_name="policyrenewal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("validity_to__isnull", True)),
                fields=("policy", "validity_to"),
                name="unique_policy_validity_to_null",
            ),
        ),
        migrations.AddField(
            model_name="policyrenewalmutation",
            name="mutation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="policy_renewals",
                to="core.mutationlog",
            ),
        ),
        migrations.AddField(
            model_name="policyrenewalmutation",
            name="policy_renewal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="mutations",
                to="policy.policyrenewal",
            ),
        ),
    ]
